

application:
  name: @project.artifactId@
  version: @project.version@
  stage: DEV

logging:
  level:
    org.springframework: INFO
    org.aspectj: DEBUG
    io.swagger: INFO
    ch.sbb.esta: DEBUG


spring:
  jackson:
    default-property-inclusion: NON_EMPTY
  cloud:
    stream:
      function:
        definition: bookSupplierV1;bookFunctionV1;bookConsumerV1;bookRawXmlConsumerV1;bookRawJsonConsumerV1
      default:
        group:  esta-scs.scs
        consumer:
          concurrency: 2
      binders:
        solace1:
          type: solace
          environment:
            solace:
              java:
                host: ${SOLACE_HOSTS}
                msgVpn: ${SOLACE_MSG_VPN}
                clientUsername: ${SOLACE_USERNAME}
                clientPassword: ${SOLACE_PASSWORD}
                clientName: @project.artifactId@
                connectRetries: 5
                reconnectRetries: 2
        kafka:
          type: kafka
      bindings:
        bookSupplierV1-out-0:
          destination: v1/bookJson
          binder: solace1
        bookFunctionV1-in-0:
          destination: v1/bookJson
          consumer:
            concurrency: 4
          binder: solace1
        bookFunctionV1-out-0:
          destination: v1/bookXml
          contentType: "application/xml"
          producer:
            msgTtl: 20000 # TODO make it work
          binder: solace1
        bookConsumerV1-in-0:
          destination: v1/bookXml
          contentType: "application/xml"
          binder: solace1
          # routing-expression: "headers['type']=='order'" # has no effect
          #routing-expression:  spring.cloud.function.routing-expression header to value T(java.lang.System).currentTimeMillis() % 2 == 0 ? 'even' : 'odd'
        bookRawXmlConsumerV1-in-0:
          destination: v1/bookXml
          group:  esta-scs.rawxml
          contentType: "application/xml"
          binder: solace1
        bookRawJsonConsumerV1-in-0:
          destination: v1/bookJson
          group: rawjson
          binder: solace1
      solace:
        default:
          prefix: escs/${application.stage}/
          producer:
            prefix: ${spring.cloud.stream.solace.default.prefix}
            msgTtl: 15000
            msgInternalDmqEligible: true
          consumer:
            prefix: ${spring.cloud.stream.solace.default.prefix}
            autoBindDmq: true



springdoc:
  swagger-ui:
    path: /swagger-ui.html


management:
  health:
    binders:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
      cache:
        time-to-live: 'PT60s'
    env:
      cache:
        time-to-live:
  endpoints:
    jmx:
      exposure:
        include: metrics
    web:
      exposure:
        include: health,info,metrics,prometheus
server:
  port: 8088
